### ISSUE TITLE
`asdf list-all pandoc` does not list all Pandoc versions (Pandoc does not follow SemVer)

### ISSUE THREAD

**Issue by StephanMeijer** [Fbrisset/asdf-pandoc#5]
**Describe the bug**

`asdf list-all pandoc` does not list all Pandoc versions

**Steps to reproduce**

```
$ asdf list-all pandoc
```

<details>

<summary>Output</summary>

```
1.2.1
1.5.1
1.8.1
1.8.2
1.9.1
1.9.3
1.9.4
1.10.1
1.11.1
1.12.1
1.12.2
1.12.3
1.12.4
1.13.1
1.13.2
1.14.1
1.15.1
1.15.2
1.17.1
1.17.02
1.17.2
1.19.1
1.19.2
2.0.1
2.0.2
2.0.3
2.0.4
2.0.5
2.0.6
2.1.1
2.1.2
2.1.3
2.2.1
2.2.2
2.2.3
2.3.1
2.7.1
2.7.2
2.7.3
2.8.1
2.9.1
2.9.2
2.10.1
2.11.1
2.11.2
2.11.3
2.11.4
2.14.1
2.14.2
2.16.1
2.16.2
2.17.1
2.19.1
2.19.2
3.0.1
3.1.1
3.1.2
3.1.3
3.1.4
3.1.5
3.1.6
3.1.7
3.1.8
3.1.9
3.1.10
3.1.11
3.1.12
3.1.13
```

</details>

**Expected behavior**

It would be expected to list all versions. **Pandoc does not follow semantic versioning.** You can expect versions like: `3.2` or `3.1.12.3`. See https://github.com/jgm/pandoc/tags

**Additional context**

Please see https://github.com/jgm/pandoc/issues/9810

**Comment by alerque** [comment]
Pandoc (along with virtually every other Haskell project in the world) uses the [HPVP](https://pvp.haskell.org/) scheme, not semver. There are actually quite a few non-Haskell projects that follow the same or similar schemes.

**Comment by StephanMeijer** [comment]
> Pandoc (along with virtually every other Haskell project in the world) uses the [HPVP](https://pvp.haskell.org/) scheme, not semver. There are actually quite a few non-Haskell projects that follow the same or similar schemes.

Correct. The pull request I created would fix that.

**Comment by Fbrisset** [comment]
Fix is merged.
